planner/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from planner.custom_decorators import access_private_garden, custom_login_required
from .views import *

app_name = 'planner'

urlpatterns = [
    path('', index, name='index'),

    # PWA offline page
    path('offline', PWAOfflineView.as_view(), name='pwa_offline_page'),

    # Authentications views
    path('login', auth_views.login, {'template_name': 'planner/login.html'}, name='login'),
    path('signup', signup, name='signup'),
    path('garden_selection', custom_login_required(GardenSelectionView.as_view()), name='garden_selection'),
    path('logout', log_out, name="log_out"),

    # Beds management
    path('<int:garden_id>/create_bed', access_private_garden(BedCreateView.as_view()), name='create_bed'),
    path('<int:garden_id>/update_bed/<int:pk>', access_private_garden(BedUpdateView.as_view()),
         name='update_bed'),
    path('<int:garden_id>/delete_bed/<int:pk>', access_private_garden(BedDelete.as_view()),
         name='delete_bed'),
    path('<int:garden_id>/create_parcel', access_private_garden(ParcelCreateView.as_view()), name='create_parcel'),
    path('<int:garden_id>/update_parcel/<int:pk>', access_private_garden(ParcelUpdateView.as_view()),
         name='update_parcel'),
    path('<int:garden_id>/delete_parcel/<int:pk>', access_private_garden(ParcelDelete.as_view()),
         name='delete_parcel'),
    path('<int:garden_id>', access_private_garden(GardenView.as_view()), name='garden_view'),
    path('<int:garden_id>/save_bed_position', access_private_garden(SaveBedPosition.as_view()),
         name='save_bed_position'),

    # QR codes logic
    path('<int:garden_id>/qr/<int:pk>', access_private_garden(BedQRView.as_view()), name="qr_bed_view"),
    path('<int:garden_id>/qr_area/<int:pk>', access_private_garden(OperationByAreaQRView.as_view()),
         name="qr_area_view"),
    path('<int:garden_id>/print_qr', access_private_garden(PrintQRView.as_view()), name="print_qr_codes"),

    # Crops management
    path('<int:garden_id>/crops', access_private_garden(CropsIndexView.as_view()), name='crops_view'),
    path('<int:garden_id>/crops/vegetables_based', access_private_garden(CropsByVegetableView.as_view()),
         name='crops_by_vegetable_view'),
    path('<int:garden_id>/<int:area_id>/terminate_cropping',
         access_private_garden(DeactivateCultivatedArea.as_view()),
         name='deactivate_cultivated_area_view'),

    # Alerts views
    path('<int:garden_id>/alerts', access_private_garden(AlertView.as_view()), name='alerts_view'),
    path('<int:garden_id>/alerts/add_seed', access_private_garden(AddSeed.as_view()), name='add_seed_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/validate', access_private_garden(ValidateAlert.as_view()),
         name='validate_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/postpone', access_private_garden(PostponeAlert.as_view()),
         name='postpone_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/delete', access_private_garden(DeleteAlert.as_view()),
         name='delete_alert_view'),
    path('<int:garden_id>/alerts/add_punctual_operation',
         access_private_garden(AddPunctualOperationView.as_view()),
         name='add_punctual_operation'),
    path('<int:garden_id>/alerts/add_observation', access_private_garden(AddObservationView.as_view()),
         name='add_observation'),

    # Print Alerts view
    path('<int:garden_id>/alerts/print', access_private_garden(PrintForthcomingOperations.as_view()),
         name='print_forthcoming_operations'),

    # Vegetables view
    path('<int:garden_id>/vegetables', access_private_garden(VegetablesView.as_view()), name='vegetables_view'),
    path('<int:garden_id>/vegetables/new', access_private_garden(AddVegetableView.as_view()),
         name='add_vegetable_to_garden_view'),
    path('<int:garden_id>/delete_vegetable/<int:pk>', access_private_garden(VegetableDelete.as_view()),
         name='delete_vegetable'),
    path('<int:garden_id>/update_vegetable/<int:pk>', access_private_garden(VegetableUpdateView.as_view()),
         name='update_vegetable'),

    # Cultural operations management
    path('<int:garden_id>/vegetables/delete_co/<int:co_id>', access_private_garden(CulturalOperationDelete.as_view()),
         name='delete_co'),
    path('<int:garden_id>/co/<int:co_id>', access_private_garden(EditCulturalOperationView.as_view()),
         name='edit_co_view'),
    path('<int:garden_id>/pick_co/<int:v_id>', access_private_garden(PickCOType.as_view()), name='pick_co_type'),
    path('<int:garden_id>/<int:vegetable_id>/add_date_co',
         access_private_garden(CulturalOperationWithDateCreate.as_view()),
         name='add_date_co_view'),
    path('<int:garden_id>/<int:vegetable_id>/add_offset_co',
         access_private_garden(CulturalOperationWithOffsetCreate.as_view()),
         name='add_offset_co_view'),

    # Garden management
    path('<int:garden_id>/settings', access_private_garden(GardenSettings.as_view()), name='garden_settings_view'),
    path('<int:garden_id>/settings/add_user', access_private_garden(AddUserToGarden.as_view()),
         name='add_user_to_garden_view'),
    path('<int:garden_id>/settings/delete/<int:user_id>', access_private_garden(DeleteUserFromGarden.as_view()),
         name='delete_user_from_garden'),
    path('<int:garden_id>/settings/notification_delay', access_private_garden(EditNotificationDelay.as_view()),
         name='edit_notification_delay'),
    path('<int:garden_id>/settings/edit_email', access_private_garden(UserEmail.as_view()),
         name='edit_user_email'),
    path('<int:garden_id>/settings/edit_details', access_private_garden(GardenDetails.as_view()),
         name='garden_edit_details'),
    path('<int:garden_id>/settings/edit_password', access_private_garden(ChangePasswordView.as_view()),
         name='garden_edit_password'),

    # Export pages
    path('<int:garden_id>/export', access_private_garden(ExportGardenHistoryView.as_view()),
         name='garden_export_view'),
    path('<int:garden_id>/export_history', access_private_garden(ExportGardenOperationHistory.as_view()),
         name='garden_history_export_view'),
    path('<int:garden_id>/export_harvest', access_private_garden(ExportGardenHarvests.as_view()),
         name='garden_harvest_export_view'),
    path('<int:garden_id>/export_entry_register', access_private_garden(ExportGardenEntryRegister.as_view()),
         name='garden_entry_register_export'),
    path('<int:garden_id>/export_usage_register', access_private_garden(ExportGardenUsageRegister.as_view()),
         name='garden_usage_register_export'),

    # Statistics page
    path('<int:garden_id>/statistics', access_private_garden(GardenStatisticsView.as_view()),
         name='garden_statistics_view'),

    # Import from library view
    path('<int:garden_id>/import_vegetables', access_private_garden(ImportVegetablesView.as_view()),
         name='garden_import_vegetables_view'),
    path('<int:garden_id>/import_vegetables/select', access_private_garden(SelectVegetablesToImportView.as_view()),
         name='select_vegetables_to_import_view'),

    # Phytosanitary views
    path('<int:garden_id>/phytosanitaire', access_private_garden(PhytosanitaryView.as_view()),
         name='phytosanitary_view'),
    path('<int:garden_id>/create_phytosanitaire', access_private_garden(CreatePhytosanitaryView.as_view()),
         name='create_phytosanitary_entry'),
    path('<int:garden_id>/delete_phytosanitaire/<int:pk>', access_private_garden(DeletePhytosanitaryView.as_view()),
         name='delete_phytosanitary_entry'),
    path('<int:garden_id>/edit_phytosanitaire/<int:pk>', access_private_garden(UpdatePhytosanitaryView.as_view()),
         name='update_phytosanitary_entry'),
    path('<int:garden_id>/create_phytosanitaire_usage', access_private_garden(CreatePhytosanitaryUsage.as_view()),
         name='create_phytosanitary_usage'),
    path('<int:garden_id>/delete_phytosanitaire_usage/<int:pk>',
         access_private_garden(DeletePhytosanitaryUsage.as_view()),
         name='delete_phytosanitary_usage'),
    path('<int:garden_id>/edit_phytosanitaire_usage/<int:pk>',
         access_private_garden(UpdatePhytosanitaryUsage.as_view()),
         name='update_phytosanitary_usage'),

    # Contact modal
    path('contact', ContactView.as_view(), name='contact_info'),

]

vegetables_library/urls.py
from django.urls import path

from vegetables_library import views
from vegetables_library.views import AddVegetableView, EditCulturalOperationView, CulturalOperationWithDateCreate, \
    CulturalOperationWithOffsetCreate, PickCOTypeView, DeleteCOView

app_name = 'vegetables_library'

urlpatterns = [

    path('', views.index, name='index'),
    path('vegetables/delete_co/<int:co_id>', DeleteCOView.as_view(), name='delete_co'),
    path('add_vegetable', AddVegetableView.as_view(), name='add_vegetable_to_library_view'),
    path('co/<int:co_id>', EditCulturalOperationView.as_view(), name='edit_co_view'),
    path('pick_co/<int:vegetable_id>', PickCOTypeView.as_view(), name='pick_co_type'),
    path('<int:vegetable_id>/add_date_co', CulturalOperationWithDateCreate.as_view(), name='add_date_co_view'),
    path('<int:vegetable_id>/add_offset_co', CulturalOperationWithOffsetCreate.as_view(), name='add_offset_co_view'),

]

vegetables_library/forms.py
from django.forms import ModelForm, DateInput, TimeInput

from vegetables_library.models import Variety, COWithDate, COWithOffset


class CustomDateInput(DateInput):
    """ Class overwriting the DateInput class of django.forms to change the input type of DateFields to date """
    input_type = 'date'


class CustomTimeInput(TimeInput):
    """ Class overwriting the TimeInput class of django.forms to change the input type of DurationField to time """
    input_type = 'time'


class VegetableForm(ModelForm):
    """ Model form based on the Vegetable model """
    class Meta:
        model = Variety
        fields = ['french_name', 'latin_name']


class CODateForm(ModelForm):
    """ Model form based for the Cultural Operation with dates model """
    class Meta:
        model = COWithDate
        fields = ['name', 'vegetable', 'absoluteDate', 'duration']
        widgets = {
            'absoluteDate': CustomDateInput(),
            # Show seconds for duration input field
            # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attribute
            'duration': CustomTimeInput(attrs={'step': 1}),
        }


class COOffsetForm(ModelForm):
    """ Model form based for the Cultural Operation with offset model """
    class Meta:
        model = COWithOffset
        fields = ['name', 'vegetable', 'previous_operation', 'offset_in_days', 'duration']
        widgets = {
            'duration': CustomTimeInput(attrs={'step': 1}),
        }

vegetables_library/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import FormView, CreateView

from vegetables_library.forms import VegetableForm, CustomTimeInput, CustomDateInput, CODateForm, COOffsetForm
from vegetables_library.models import Variety, CulturalOperation, COWithOffset, COWithDate, Species


def index(request):
    species = Species.objects.values()
    cultural_operations = CulturalOperation.objects.select_subclasses()
    context = {'species': species, "cultural_operations": cultural_operations}
    return render(request, 'vegetables_library/vegetables_list.html', context=context)


class AddVegetableView(FormView):
    template_name = 'vegetables_library/modals/add_vegetable_to_library_form.html'
    form_class = VegetableForm

    def get(self, request, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def get_success_url(self):
        return reverse_lazy('vegetables_library:index', kwargs=self.kwargs)

    def form_valid(self, form):
        new_vege = form.save()
        return super().form_valid(form)


class CulturalOperationCreate(CreateView):
    template_name = "vegetables_library/create_co_form.html"

    def form_valid(self, form):
        response = super(CulturalOperationCreate, self).form_valid(form)
        return response

    def get_initial(self):
        return {'vegetable': self.kwargs['vegetable_id']}

    def get_success_url(self):
        return reverse_lazy('vegetables_library:index')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(CulturalOperationCreate, self).get_context_data(**kwargs)
        return context


class CulturalOperationWithDateCreate(CulturalOperationCreate):
    template_name = "vegetables_library/create_co_form.html"
    model = COWithDate
    fields = ['name', 'vegetable', 'absoluteDate', 'duration']

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        form = super(CulturalOperationWithDateCreate, self).get_form(form_class)
        form.fields['absoluteDate'].widget = CustomDateInput()
        # Show seconds for duration input field
        # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time#Using_the_step_attribute
        form.fields['duration'].widget = CustomTimeInput(attrs={'step': 1})
        return form


class CulturalOperationWithOffsetCreate(CulturalOperationCreate):
    template_name = "vegetables_library/create_co_form.html"
    model = COWithOffset
    fields = ['name', 'vegetable', 'previous_operation', 'offset_in_days', 'duration']


class EditCulturalOperationView(View):
    template_name = 'vegetables_library/modals/edit_co_form.html'

    def get(self, request, **kwargs):
        co = CulturalOperation.objects.select_subclasses().get(pk=kwargs['co_id'])
        if isinstance(co, COWithDate):
            form = CODateForm(instance=co)
        else:
            form = COOffsetForm(instance=co)
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        # create a form instance and populate it with data from the request:
        co = CulturalOperation.objects.select_subclasses().get(pk=kwargs['co_id'])
        if isinstance(co, COWithDate):
            form = CODateForm(request.POST, instance=co)
        else:
            form = COOffsetForm(request.POST, instance=co)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            success_message = 'L\'opération \" {} \" a bien été modifiée'.format(co.name)
            messages.add_message(request, messages.SUCCESS, success_message)
            return HttpResponseRedirect(reverse('vegetables_library:index'))


class PickCOTypeView(View):
    template_name = 'vegetables_library/modals/pick_co_type_form.html'

    def get(self, request, **kwargs):
        context = {'vegetable': kwargs['vegetable_id']}
        return render(request, self.template_name, context)

    def post(self, request, **kwargs):
        if request.POST['cotype'] == 'offsetco':
            return HttpResponseRedirect(reverse('vegetables_library:add_offset_co_view', kwargs=kwargs))
        else:
            return HttpResponseRedirect(reverse('vegetables_library:add_date_co_view', kwargs=kwargs))


class DeleteCOView(View):
    def get(self, request, **kwargs):
        CulturalOperation.objects.select_subclasses().get(pk=kwargs['co_id']).delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

vegetables_library/templates/vegetables_library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lauzeplan - Base de données de légumes</title>

    {% load static %}
    <!-- Icons -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static '/planner/icons/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static '/planner/icons/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/planner/icons/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static '/planner/icons/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/planner/icons/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static '/planner/icons/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static '/planner/icons/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static '/planner/icons/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static '/planner/icons/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static '/planner/icons/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static '/planner/icons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static '/planner/icons/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static '/planner/icons/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"
            integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "planner/css/style.css" %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


    {% block extra_js %}{% endblock extra_js %}

</head>
<body>
<div class="body-wrap">
    {% load planner_extras %}

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <div class="navbar-logos">
                    <a class="navbar-brand" href="">
                        <img alt="LauzePlan" src="{% static '/planner/icons/apple-icon-57x57.png' %}">
                    </a>
                    <a class="navbar-brand" href="">
                        LauzePlan - Base de données de légumes
                    </a>
                </div>
                <!-- Hamburger button -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="navbar-date">{% now "D d F Y" %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-container">

        {% block content %}{% endblock content %}

    </div>

</div>

</body>
</html>

vegetables_library/templates/vegetables_library/create_co_form.html
{% extends "vegetables_library/base.html" %}

{% block content %}

    {% load crispy_forms_tags %}
    <form action="" name="" role="form" class="form-horizontal col-md-6" method="post" accept-charset="utf-8">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Créer"/>
    </form>


{% endblock content %}

vegetables_library/templates/vegetables_library/vegetables_list.html
{% extends 'vegetables_library/base.html' %}


{% block content %}
    {% load planner_extras %}


    {% if messages %}
        <div class="container">

                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        {{ message }}
                    </div>
                {% endfor %}

        </div>
    {% endif %}

    <!-- Modal -->
    <div class="modal fade" id="modal-edit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-pick-type" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div><!-- /.modal -->

    <div class="modal fade" id="modal-add_vegetable" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
{##}
{#    <div class="container">#}
{#        <a class="btn btn-success margin-button" data-toggle="modal"#}
{#           href="{% url 'vegetables_library:add_vegetable_to_library_view' %}"#}
{#           data-target="#modal-add_vegetable" title="Ajouter un légume" data-tooltip>#}
{#            <i class="fas fa-fw fa-plus"></i>#}
{#            Ajouter un légume#}
{#        </a>#}
{##}
{#    </div>#}

    {% if species %}
        {% load planner_extras %}
        <div class="container">
            <div class="panel-group">
                <div class="panel panel-primary">
                    {% for s in species %}
                        <div class="panel-heading">
                            <h4 data-toggle="collapse" href="#collapse-v{{ s.id }}" class="panel-title clickable">
                                <span>{{ s.french_name }} <span class="pull-right"><i class="fas fa-fw fa-chevron-down"></i></span></span>
                            </h4>

                        </div>
                        <div id="collapse-v{{ s.id }}" class="panel-collapse collapse">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Legume</th>
                                        <th>Nom latin</th>
                                    </tr>
                                    </thead>
                                    {% for v in s.id|varieties_from_species %}
                                        <tbody>
                                        <tr>
                                            <td>{{ v.french_name }}</td>

                                            <td>{{ v.latin_name }}</td>


                                        </tbody>
                                    {% endfor %}
                                </table>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    {% endif %}

    {% load static %}
    <script src="{% static 'planner/js/activate_modal.js' %}"></script>


{% endblock content %}