planner/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from planner.custom_decorators import access_private_garden, custom_login_required
from .views import *

app_name = 'planner'

urlpatterns = [
    path('', index, name='index'),

    # PWA offline page
    path('offline', PWAOfflineView.as_view(), name='pwa_offline_page'),

    # Authentications views
    path('login', auth_views.login, {'template_name': 'planner/login.html'}, name='login'),
    path('signup', signup, name='signup'),
    path('garden_selection', custom_login_required(GardenSelectionView.as_view()), name='garden_selection'),
    path('logout', log_out, name="log_out"),

    # Beds management
    path('<int:garden_id>/create_bed', access_private_garden(BedCreateView.as_view()), name='create_bed'),
    path('<int:garden_id>/update_bed/<int:pk>', access_private_garden(BedUpdateView.as_view()),
         name='update_bed'),
    path('<int:garden_id>/delete_bed/<int:pk>', access_private_garden(BedDelete.as_view()),
         name='delete_bed'),
    path('<int:garden_id>/create_parcel', access_private_garden(ParcelCreateView.as_view()), name='create_parcel'),
    path('<int:garden_id>/update_parcel/<int:pk>', access_private_garden(ParcelUpdateView.as_view()),
         name='update_parcel'),
    path('<int:garden_id>/delete_parcel/<int:pk>', access_private_garden(ParcelDelete.as_view()),
         name='delete_parcel'),
    path('<int:garden_id>', access_private_garden(GardenView.as_view()), name='garden_view'),
    path('<int:garden_id>/save_bed_position', access_private_garden(SaveBedPosition.as_view()),
         name='save_bed_position'),

    # QR codes logic
    path('<int:garden_id>/qr/<int:pk>', access_private_garden(BedQRView.as_view()), name="qr_bed_view"),
    path('<int:garden_id>/qr_area/<int:pk>', access_private_garden(OperationByAreaQRView.as_view()),
         name="qr_area_view"),
    path('<int:garden_id>/print_qr', access_private_garden(PrintQRView.as_view()), name="print_qr_codes"),

    # Crops management
    path('<int:garden_id>/crops', access_private_garden(CropsIndexView.as_view()), name='crops_view'),
    path('<int:garden_id>/crops/vegetables_based', access_private_garden(CropsByVegetableView.as_view()),
         name='crops_by_vegetable_view'),
    path('<int:garden_id>/<int:area_id>/terminate_cropping',
         access_private_garden(DeactivateCultivatedArea.as_view()),
         name='deactivate_cultivated_area_view'),

    # Alerts views
    path('<int:garden_id>/alerts', access_private_garden(AlertView.as_view()), name='alerts_view'),
    path('<int:garden_id>/alerts/add_seed', access_private_garden(AddSeed.as_view()), name='add_seed_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/validate', access_private_garden(ValidateAlert.as_view()),
         name='validate_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/postpone', access_private_garden(PostponeAlert.as_view()),
         name='postpone_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/delete', access_private_garden(DeleteAlert.as_view()),
         name='delete_alert_view'),
    path('<int:garden_id>/alerts/add_punctual_operation',
         access_private_garden(AddPunctualOperationView.as_view()),
         name='add_punctual_operation'),
    path('<int:garden_id>/alerts/add_observation', access_private_garden(AddObservationView.as_view()),
         name='add_observation'),

    # Print Alerts view
    path('<int:garden_id>/alerts/print', access_private_garden(PrintForthcomingOperations.as_view()),
         name='print_forthcoming_operations'),

    # Vegetables view
    path('<int:garden_id>/vegetables', access_private_garden(VegetablesView.as_view()), name='vegetables_view'),
    path('<int:garden_id>/vegetables/new', access_private_garden(AddVegetableView.as_view()),
         name='add_vegetable_to_garden_view'),
    path('<int:garden_id>/delete_vegetable/<int:pk>', access_private_garden(VegetableDelete.as_view()),
         name='delete_vegetable'),
    path('<int:garden_id>/update_vegetable/<int:pk>', access_private_garden(VegetableUpdateView.as_view()),
         name='update_vegetable'),

    # Cultural operations management
    path('<int:garden_id>/vegetables/delete_co/<int:co_id>', access_private_garden(CulturalOperationDelete.as_view()),
         name='delete_co'),
    path('<int:garden_id>/co/<int:co_id>', access_private_garden(EditCulturalOperationView.as_view()),
         name='edit_co_view'),
    path('<int:garden_id>/pick_co/<int:v_id>', access_private_garden(PickCOType.as_view()), name='pick_co_type'),
    path('<int:garden_id>/<int:vegetable_id>/add_date_co',
         access_private_garden(CulturalOperationWithDateCreate.as_view()),
         name='add_date_co_view'),
    path('<int:garden_id>/<int:vegetable_id>/add_offset_co',
         access_private_garden(CulturalOperationWithOffsetCreate.as_view()),
         name='add_offset_co_view'),

    # Garden management
    path('<int:garden_id>/settings', access_private_garden(GardenSettings.as_view()), name='garden_settings_view'),
    path('<int:garden_id>/settings/add_user', access_private_garden(AddUserToGarden.as_view()),
         name='add_user_to_garden_view'),
    path('<int:garden_id>/settings/delete/<int:user_id>', access_private_garden(DeleteUserFromGarden.as_view()),
         name='delete_user_from_garden'),
    path('<int:garden_id>/settings/notification_delay', access_private_garden(EditNotificationDelay.as_view()),
         name='edit_notification_delay'),
    path('<int:garden_id>/settings/edit_email', access_private_garden(UserEmail.as_view()),
         name='edit_user_email'),
    path('<int:garden_id>/settings/edit_details', access_private_garden(GardenDetails.as_view()),
         name='garden_edit_details'),
    path('<int:garden_id>/settings/edit_password', access_private_garden(ChangePasswordView.as_view()),
         name='garden_edit_password'),

    # Export pages
    path('<int:garden_id>/export', access_private_garden(ExportGardenHistoryView.as_view()),
         name='garden_export_view'),
    path('<int:garden_id>/export_history', access_private_garden(ExportGardenOperationHistory.as_view()),
         name='garden_history_export_view'),
    path('<int:garden_id>/export_harvest', access_private_garden(ExportGardenHarvests.as_view()),
         name='garden_harvest_export_view'),
    path('<int:garden_id>/export_entry_register', access_private_garden(ExportGardenEntryRegister.as_view()),
         name='garden_entry_register_export'),
    path('<int:garden_id>/export_usage_register', access_private_garden(ExportGardenUsageRegister.as_view()),
         name='garden_usage_register_export'),

    # Statistics page
    path('<int:garden_id>/statistics', access_private_garden(GardenStatisticsView.as_view()),
         name='garden_statistics_view'),

    # Import from library view
    path('<int:garden_id>/import_vegetables', access_private_garden(ImportVegetablesView.as_view()),
         name='garden_import_vegetables_view'),
    path('<int:garden_id>/import_vegetables/select', access_private_garden(SelectVegetablesToImportView.as_view()),
         name='select_vegetables_to_import_view'),

    # Phytosanitary views
    path('<int:garden_id>/phytosanitaire', access_private_garden(PhytosanitaryView.as_view()),
         name='phytosanitary_view'),
    path('<int:garden_id>/create_phytosanitaire', access_private_garden(CreatePhytosanitaryView.as_view()),
         name='create_phytosanitary_entry'),
    path('<int:garden_id>/delete_phytosanitaire/<int:pk>', access_private_garden(DeletePhytosanitaryView.as_view()),
         name='delete_phytosanitary_entry'),
    path('<int:garden_id>/edit_phytosanitaire/<int:pk>', access_private_garden(UpdatePhytosanitaryView.as_view()),
         name='update_phytosanitary_entry'),
    path('<int:garden_id>/create_phytosanitaire_usage', access_private_garden(CreatePhytosanitaryUsage.as_view()),
         name='create_phytosanitary_usage'),
    path('<int:garden_id>/delete_phytosanitaire_usage/<int:pk>',
         access_private_garden(DeletePhytosanitaryUsage.as_view()),
         name='delete_phytosanitary_usage'),
    path('<int:garden_id>/edit_phytosanitaire_usage/<int:pk>',
         access_private_garden(UpdatePhytosanitaryUsage.as_view()),
         name='update_phytosanitary_usage'),

    # Contact modal
    path('contact', ContactView.as_view(), name='contact_info'),

]

planner/views/alerts_views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import View
from django.views.generic import TemplateView, FormView

from .generic_views_overwritten import OperationsOnAlertViews
from planner import queries, services, generate_pdf_helper
from planner.forms import ForthcomingOperationsDelayForm
from planner.models import Garden, Vegetable, Bed, ForthcomingOperation, Parcel


class AlertView(TemplateView):
    template_name = 'planner/alerts.html'

    def get(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        alerts = queries.get_currently_active_alerts(garden_id)
        history = queries.done_alerts(garden_id)
        context = {'alerts': alerts, 'history': history}
        return render(request, self.template_name, context)


class AddSeed(View):
    """ GET : This class renders a form to add a plantation to the current garden
        POST: this class add a vegetable plantation on a specific surface of the garden"""

    def get(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        vegetables = Vegetable.objects.filter(garden_id=garden_id)
        surfaces = Bed.objects.filter(garden_id=garden_id)
        parcels = Parcel.objects.filter(garden_id=garden_id)
        context = {'vegetables': vegetables, 'surfaces': surfaces, 'parcels': parcels}
        return render(request, 'planner/modals/add_seeding_form.html', context)

    def post(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        vegetable_id = request.POST['vegetable_selection']
        vegetable_concerned = Vegetable.objects.get(pk=vegetable_id).name
        garden = Garden.objects.get(pk=garden_id)
        beds_id = request.POST.getlist('multiple_beds_selection')
        for b in beds_id:
            if services.add_new_plantation_to_alerts(garden=garden, vegetable_id=vegetable_id,
                                                     label=request.POST['seeding_label'],
                                                     surface_id=b):
                success_message = 'Vous ({}) avez ajouté une plantation de {} '.format(
                    request.user.username, vegetable_concerned)
                messages.add_message(request, messages.SUCCESS, success_message)
            else:
                warning_message = 'Cette planche a déjà une plantation de {} active, avec le même label '.format(
                    vegetable_concerned)
                messages.add_message(request, messages.WARNING, warning_message)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class ValidateAlert(OperationsOnAlertViews):
    template_name = 'planner/modals/validate_alert_form.html'

    def post(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        alert_id = kwargs['alert_id']
        executor = request.user
        execution_date = request.POST['execution_date']
        note = request.POST['validation_note']
        duration = request.POST['duration']
        services.mark_operation_as_done(operation_id=alert_id, execution_date=execution_date, executor=executor,
                                        note=note, duration=duration)
        alert_name = ForthcomingOperation.objects.get(pk=alert_id)
        success_message = 'Vous ({}) avez indiqué avoir effectué l\'opération \" {} \" le {}'.format(
            request.user.username, alert_name, execution_date)
        messages.add_message(request, messages.SUCCESS, success_message)
        return HttpResponseRedirect(reverse('planner:alerts_view', kwargs={'garden_id': garden_id}))


class PostponeAlert(OperationsOnAlertViews):
    template_name = 'planner/modals/postpone_alert_form.html'

    def post(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        alert_id = kwargs['alert_id']
        postponement = request.POST['postponement_in_days']
        services.postpone_alert(alert_id, postponement)
        alert_name = ForthcomingOperation.objects.get(pk=alert_id)
        success_message = 'Vous avez bien reporté l\'opération \" {} \" de {} jours'.format(alert_name, postponement)
        messages.add_message(request, messages.SUCCESS, success_message)
        return HttpResponseRedirect(reverse('planner:alerts_view', kwargs={'garden_id': garden_id}))


class DeleteAlert(OperationsOnAlertViews):
    template_name = 'planner/modals/delete_alert_form.html'

    def post(self, request, **kwargs):
        garden_id = kwargs['garden_id']
        alert_id = kwargs['alert_id']
        reason = request.POST['deletion_justification']
        note = request.POST['note']
        executor = request.user
        services.delete_operation_with_reason(alert_id, executor, reason, note)
        alert_name = ForthcomingOperation.objects.get(pk=alert_id)
        success_message = 'Vous ({}) avez supprimé l\'opération \" {} \"'.format(request.user.username, alert_name)
        messages.add_message(request, messages.SUCCESS, success_message)
        return HttpResponseRedirect(reverse('planner:alerts_view', kwargs={'garden_id': garden_id}))


class PrintForthcomingOperations(FormView):
    template_name = 'planner/modals/choose_period_to_print.html'
    form_class = ForthcomingOperationsDelayForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        garden_id = kwargs['garden_id']
        days_period = request.POST['delay_to_print']
        int_period = int(days_period)
        operations_to_print = queries.get_alert_within_notification_period(garden_id, int_period)

        return generate_pdf_helper.render_html_template_to_pdf(
            'planner/printable/print_forthcoming_operations_template.html',
            {
                'pagesize': 'A4',
                'operations': operations_to_print,
                'garden_id': garden_id,
            })

planner/views/authentication_views.py
from django.contrib import messages
from django.contrib.auth import logout, login
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.base import View

from planner.forms import GardenForm
from planner.models import Garden


def index(request):
    if request.user.is_authenticated:
        form = GardenForm()
        return HttpResponseRedirect('garden_selection', {'form': form})
    return HttpResponseRedirect('login')


def signup(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        mail = request.POST['mailaddress']
        try:
            user = User.objects.create_user(username=username, password=password, email=mail)
            login(request, user)
            return HttpResponseRedirect('garden_selection')
        except IntegrityError:
            messages.error(request, 'Le nom d\'utilisateur existe deja')
            return render(request, 'planner/signup.html')

    else:
        return render(request, 'planner/signup.html')


def log_out(request):
    logout(request)
    return HttpResponseRedirect("/login")


class GardenSelectionView(View):
    template_name = 'planner/garden_selection.html'
    form_class = GardenForm

    def get(self, request):
        form = self.form_class()
        gardens_followed = Garden.objects.filter(users=request.user)
        is_searcher = request.user.has_perm('is_researcher')
        context = {'form': form, 'gardens_followed': gardens_followed, 'is_searcher': is_searcher}
        return render(request, self.template_name, context)

    def post(self, request):
        # create a form instance and populate it with data from the request:
        form = self.form_class(request.POST)
        # check whether it's valid:
        if form.is_valid():
            new_garden = form.save(commit=False)
            new_garden.reference_email = request.user.email
            new_garden.save()
            new_garden.users.add(request.user)
            nextpage = new_garden.get_absolute_url()
            return HttpResponseRedirect(nextpage)

planner/views/contact_views.py
from django.views.generic import TemplateView


class ContactView(TemplateView):
    template_name = 'planner/modals/contact_modal.html'

planner/views/history_views.py
from .generic_views_overwritten import AddHistoryItemView
from planner.forms import OperationForm, ObservationForm


class AddPunctualOperationView(AddHistoryItemView):
    template_name = 'planner/modals/add_punctual_operation_form.html'
    form_class = OperationForm


class AddObservationView(AddHistoryItemView):
    template_name = 'planner/modals/add_observation_form.html'
    form_class = ObservationForm

planner/views/pwa_views.py
from django.views.generic import TemplateView


class PWAOfflineView(TemplateView):
    template_name = 'planner/pwa_offline_view.html'

planner/templates/planner/alerts.html
{% extends "planner/base_for_gardens_views.html" %}

{% block page_title %}Alertes{% endblock page_title %}

{% block extra_js %}
    {% load static %}
    <script src="{% static 'planner/js/sorttable.js' %}"></script>
{% endblock extra_js %}

{% block content %}

    {% load planner_extras %}
    <div class="alert alert-info" id="info-bubble-content" style="display: none;">
        Cette page vous permet de consulter les opérations à venir et celles qui ont déjà été réalisées.
        Chaque opération a plus de détails accessibles en cliquant sur la ligne concernée.
        Le bouton <i class="fas fa-plus red"></i> vous permet d'ajouter une nouvelle plantation, une utilisation de produit phytosanitaire, une opération ponctuelle ou uneobservation.
        Une nouvelle plantation ajoutera toutes les opérations relatives au légume planté dans vos opérations à venir.
        (Pour retrouver et modifier ces opérations, rendez-vous dans l'onglet <a href="{% url 'planner:vegetables_view' garden_id %}">Mes légumes</a>)
        Ces alertes ne seront visibles qu'à partir de {% get_notification_delay garden_id %} jours avant leur date d'expiration.
        Cette valeur peut être changée dans <a href="{% url 'planner:garden_settings_view' garden_id %}">vos paramètres</a>.
        Les opérations ponctuelles et les observations vous permettent simplement de garder une trace des actions que vous faites au fur et à mesure.

    </div>

    <div id="action-buttons">
        <div class="fab-btn btn-group show-on-hover dropup">
            <div data-toggle="tooltip" data-placement="right" title="Actions" style="margin-left: 42px;">
                <button type="button" class="btn btn-danger btn-io dropdown-toggle" data-toggle="dropdown">
                    <span class="">
                      <i class="fas fa-plus"></i>
                    </span>
                </button>
            </div>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li data-toggle="tooltip" data-original-title="Ajouter une observation" data-placement="right">
                    <a class="btn btn-primary" data-toggle="modal"
                       href="{% url 'planner:add_observation' garden_id %}"
                       data-target="#modal-add_observation">
                        <i class="fas fa-fw fa-eye"></i>
                    </a>
                </li>
                <li data-toggle="tooltip" title="Ajouter une opération" data-placement="right">
                    <a class="btn btn-warning" data-toggle="modal"
                       href="{% url 'planner:add_punctual_operation' garden_id %}"
                       data-target="#modal-add_punctual_operation">
                        <i class="fas fa-fw fa-bolt"></i>
                    </a>

                </li>
                <li data-toggle="tooltip" title="Ajouter une utilisation phytopharmaceutique" data-placement="right">
                    <a class="btn btn-info" data-toggle="modal"
                       href="{% url 'planner:create_phytosanitary_usage' garden_id %}"
                       data-target="#modal-add_phytosanitary_usage">
                        <i class="fas fa-fw fa-vial"></i>
                    </a>
                </li>
                <li data-toggle="tooltip" title="Ajouter une plantation" data-placement="right">
                    <a class="btn btn-success" data-toggle="modal"
                       href="{% url 'planner:add_seed_view' garden_id %}"
                       data-target="#modal-add_seed">
                        <i class="fas fa-fw fa-leaf"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    {% if messages %}
        <div class="col-md-7">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade in">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}


    <!-- Modal -->
    <div class="modal fade" id="modal-add_phytosanitary_usage" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-add_seed" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-validate_alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-postpone_alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-delete_alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-add_punctual_operation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-add_observation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-print_operations" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <!-- Modal -->

    <div class="col-md-7">


        {% load l10n %}
        <div class="panel panel-default ">
            <div class="panel-heading">Opérations à faire
                <a href="{% url 'planner:print_forthcoming_operations' garden_id %}"
                   class="pull-right blue"
                   data-toggle="modal"
                   data-target="#modal-print_operations" title="Imprimer la feuille les opérations à faire"
                   data-tooltip>
                    <i class="fas fa-fw fa-print"></i>
                </a>
            </div>
            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Plantation</th>
                            <th>Légume</th>
                            <th>Action</th>
                            <th> A faire le</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for current_alert in alerts %}
                            <tr data-toggle="collapse" href="#collapse-a{{ current_alert.id }}" class="clickable">
                                <td><b>{{ current_alert.area_concerned.label }} </b></td>
                                <td>{{ current_alert.area_concerned.vegetable }}</td>
                                <td>{{ current_alert.original_cultural_operation.name }}</td>
                                <td>{% due_date current_alert garden_id as current_due_date %} {{ current_due_date|date:"j F" }} </td>
                                <td>
                                    <a class="" data-toggle="modal"
                                       href="{% url 'planner:validate_alert_view' garden_id current_alert.id %}"
                                       data-target="#modal-validate_alert" title="Valider l'action"
                                       data-tooltip>
                                        <i class="fas fa-fw fa-check"></i>
                                    </a>
                                    <a class="" data-toggle="modal"
                                       href="{% url 'planner:postpone_alert_view' garden_id current_alert.id %}"
                                       data-target="#modal-postpone_alert" title="Reporter l'action"
                                       data-tooltip>
                                        <i class="fas fa-fw fa-redo"></i>
                                    </a>
                                    <a class="" data-toggle="modal"
                                       href="{% url 'planner:delete_alert_view' garden_id current_alert.id %}"
                                       data-target="#modal-delete_alert" title="Supprimer l'action"
                                       data-tooltip>
                                        <i class="fas fa-fw fa-times"></i>
                                    </a>
                                </td>
                            </tr>
                            <tr class="info">
                                <td colspan="5" class="hiddenRow">
                                    <div class="collapse" id="collapse-a{{ current_alert.id }}">
                                        {#                                        <b> Légume : </b> {{ current_alert.area_concerned.vegetable }}#}
                                        {#                                        <br>#}
                                        <b> Planche : </b> {{ current_alert.area_concerned.surface.name }}
                                        <br>
                                        <b> Reporté de : </b> {{ current_alert.postponement }} jours
                                        <br>
                                        <b> En retard de : </b> {% days_late current_due_date %} jours
                                        <br>
                                        <b> Temps estimé : </b> {% estimated_needed_time current_alert %} heures
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class=" col-md-5 ">
        <!--<div class="align-content-center">-->
        <!--<a class="btn btn-success" data-toggle="modal"-->
        <!--href="{% url 'planner:add_punctual_operation' garden_id %}"-->
        <!--data-target="#modal-add_punctual_operation" title="Ajouter une opération ponctuelle" data-tooltip>-->
        <!--<i class="fas fa-fw fa-plus"></i>Ajouter une action-->
        <!--</a>-->
        <!--<a class="btn btn-success" data-toggle="modal"-->
        <!--href="{% url 'planner:add_observation' garden_id %}"-->
        <!--data-target="#modal-add_observation" title="Ajouter une observation" data-tooltip>-->
        <!--<i class="fas fa-fw fa-plus"></i> Ajouter une observation-->
        <!--</a>-->
        <!--<br>-->
        <!--</div>-->
        <!--<br>-->
        <div class="panel panel-default ">
            <div class="panel-heading">Historique</div>
            <div class="panel-body">

                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th>Date</th>
                        </tr>
                        </thead>
                        {% for op in history %}
                            <tbody>
                            <tr data-toggle="collapse" href="#collapse-history{{ op.id }}" class="clickable">
                                {% if op|is_operation %}
                                    <td><b>
                                        {% if op.is_deletion %}
                                            <i class="fas fa-fw fa-times red"></i>
                                        {% else %}
                                            <i class="fas fa-fw fa-check green"></i>
                                        {% endif %}
                                        {{ op.area_concerned.label }}
                                    </b> {{ op.name }}
                                    </td>
                                    <td>{{ op.execution_date }}</td>
                                {% else %}
                                    <td>
                                        <i class="fas fa-fw fa-eye blue-icon"></i>
                                        <b> Observation - </b> {{ op.area_concerned }}
                                    </td>
                                    <td>{{ op.execution_date }}</td>
                                {% endif %}
                            </tr>

                            <tr class="info">
                                <td colspan="5" class="hiddenRow">
                                    <div class="collapse" id="collapse-history{{ op.id }}">
                                        {% if op|is_operation %}
                                            <b> Légume : </b> {{ op.area_concerned.vegetable }}
                                            {#                                        <br>#}
                                            {#                                        <b> A été reporté de : </b> {{ op.postponement }} jours#}
                                            <br>
                                            <b> Opération effectuée par : </b> {{ op.executor }}
                                            <br>
                                            <b> Durée réelle: </b> {{ op.duration }}
                                            <br>
                                            <b> Commentaire éventuel : </b> {{ op.note }}
                                        {% else %}
                                            <b> Description : </b> {{ op.description }}
                                        {% endif %}
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'planner/js/activate_modal.js' %}"></script>
    <script src="{% static 'planner/js/activate_tooltips.js' %}"></script>

{% endblock content %}