planner/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path

from planner.custom_decorators import access_private_garden, custom_login_required
from .views import *

app_name = 'planner'

urlpatterns = [
    path('', index, name='index'),

    # PWA offline page
    path('offline', PWAOfflineView.as_view(), name='pwa_offline_page'),

    # Authentications views
    path('login', auth_views.login, {'template_name': 'planner/login.html'}, name='login'),
    path('signup', signup, name='signup'),
    path('garden_selection', custom_login_required(GardenSelectionView.as_view()), name='garden_selection'),
    path('logout', log_out, name="log_out"),

    # Beds management
    path('<int:garden_id>/create_bed', access_private_garden(BedCreateView.as_view()), name='create_bed'),
    path('<int:garden_id>/update_bed/<int:pk>', access_private_garden(BedUpdateView.as_view()),
         name='update_bed'),
    path('<int:garden_id>/delete_bed/<int:pk>', access_private_garden(BedDelete.as_view()),
         name='delete_bed'),
    path('<int:garden_id>/create_parcel', access_private_garden(ParcelCreateView.as_view()), name='create_parcel'),
    path('<int:garden_id>/update_parcel/<int:pk>', access_private_garden(ParcelUpdateView.as_view()),
         name='update_parcel'),
    path('<int:garden_id>/delete_parcel/<int:pk>', access_private_garden(ParcelDelete.as_view()),
         name='delete_parcel'),
    path('<int:garden_id>', access_private_garden(GardenView.as_view()), name='garden_view'),
    path('<int:garden_id>/save_bed_position', access_private_garden(SaveBedPosition.as_view()),
         name='save_bed_position'),

    # QR codes logic
    path('<int:garden_id>/qr/<int:pk>', access_private_garden(BedQRView.as_view()), name="qr_bed_view"),
    path('<int:garden_id>/qr_area/<int:pk>', access_private_garden(OperationByAreaQRView.as_view()),
         name="qr_area_view"),
    path('<int:garden_id>/print_qr', access_private_garden(PrintQRView.as_view()), name="print_qr_codes"),

    # Crops management
    path('<int:garden_id>/crops', access_private_garden(CropsIndexView.as_view()), name='crops_view'),
    path('<int:garden_id>/crops/vegetables_based', access_private_garden(CropsByVegetableView.as_view()),
         name='crops_by_vegetable_view'),
    path('<int:garden_id>/<int:area_id>/terminate_cropping',
         access_private_garden(DeactivateCultivatedArea.as_view()),
         name='deactivate_cultivated_area_view'),

    # Alerts views
    path('<int:garden_id>/alerts', access_private_garden(AlertView.as_view()), name='alerts_view'),
    path('<int:garden_id>/alerts/add_seed', access_private_garden(AddSeed.as_view()), name='add_seed_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/validate', access_private_garden(ValidateAlert.as_view()),
         name='validate_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/postpone', access_private_garden(PostponeAlert.as_view()),
         name='postpone_alert_view'),
    path('<int:garden_id>/alerts/<int:alert_id>/delete', access_private_garden(DeleteAlert.as_view()),
         name='delete_alert_view'),
    path('<int:garden_id>/alerts/add_punctual_operation',
         access_private_garden(AddPunctualOperationView.as_view()),
         name='add_punctual_operation'),
    path('<int:garden_id>/alerts/add_observation', access_private_garden(AddObservationView.as_view()),
         name='add_observation'),

    # Print Alerts view
    path('<int:garden_id>/alerts/print', access_private_garden(PrintForthcomingOperations.as_view()),
         name='print_forthcoming_operations'),

    # Vegetables view
    path('<int:garden_id>/vegetables', access_private_garden(VegetablesView.as_view()), name='vegetables_view'),
    path('<int:garden_id>/vegetables/new', access_private_garden(AddVegetableView.as_view()),
         name='add_vegetable_to_garden_view'),
    path('<int:garden_id>/delete_vegetable/<int:pk>', access_private_garden(VegetableDelete.as_view()),
         name='delete_vegetable'),
    path('<int:garden_id>/update_vegetable/<int:pk>', access_private_garden(VegetableUpdateView.as_view()),
         name='update_vegetable'),

    # Cultural operations management
    path('<int:garden_id>/vegetables/delete_co/<int:co_id>', access_private_garden(CulturalOperationDelete.as_view()),
         name='delete_co'),
    path('<int:garden_id>/co/<int:co_id>', access_private_garden(EditCulturalOperationView.as_view()),
         name='edit_co_view'),
    path('<int:garden_id>/pick_co/<int:v_id>', access_private_garden(PickCOType.as_view()), name='pick_co_type'),
    path('<int:garden_id>/<int:vegetable_id>/add_date_co',
         access_private_garden(CulturalOperationWithDateCreate.as_view()),
         name='add_date_co_view'),
    path('<int:garden_id>/<int:vegetable_id>/add_offset_co',
         access_private_garden(CulturalOperationWithOffsetCreate.as_view()),
         name='add_offset_co_view'),

    # Garden management
    path('<int:garden_id>/settings', access_private_garden(GardenSettings.as_view()), name='garden_settings_view'),
    path('<int:garden_id>/settings/add_user', access_private_garden(AddUserToGarden.as_view()),
         name='add_user_to_garden_view'),
    path('<int:garden_id>/settings/delete/<int:user_id>', access_private_garden(DeleteUserFromGarden.as_view()),
         name='delete_user_from_garden'),
    path('<int:garden_id>/settings/notification_delay', access_private_garden(EditNotificationDelay.as_view()),
         name='edit_notification_delay'),
    path('<int:garden_id>/settings/edit_email', access_private_garden(UserEmail.as_view()),
         name='edit_user_email'),
    path('<int:garden_id>/settings/edit_details', access_private_garden(GardenDetails.as_view()),
         name='garden_edit_details'),
    path('<int:garden_id>/settings/edit_password', access_private_garden(ChangePasswordView.as_view()),
         name='garden_edit_password'),

    # Export pages
    path('<int:garden_id>/export', access_private_garden(ExportGardenHistoryView.as_view()),
         name='garden_export_view'),
    path('<int:garden_id>/export_history', access_private_garden(ExportGardenOperationHistory.as_view()),
         name='garden_history_export_view'),
    path('<int:garden_id>/export_harvest', access_private_garden(ExportGardenHarvests.as_view()),
         name='garden_harvest_export_view'),
    path('<int:garden_id>/export_entry_register', access_private_garden(ExportGardenEntryRegister.as_view()),
         name='garden_entry_register_export'),
    path('<int:garden_id>/export_usage_register', access_private_garden(ExportGardenUsageRegister.as_view()),
         name='garden_usage_register_export'),

    # Statistics page
    path('<int:garden_id>/statistics', access_private_garden(GardenStatisticsView.as_view()),
         name='garden_statistics_view'),

    # Import from library view
    path('<int:garden_id>/import_vegetables', access_private_garden(ImportVegetablesView.as_view()),
         name='garden_import_vegetables_view'),
    path('<int:garden_id>/import_vegetables/select', access_private_garden(SelectVegetablesToImportView.as_view()),
         name='select_vegetables_to_import_view'),

    # Phytosanitary views
    path('<int:garden_id>/phytosanitaire', access_private_garden(PhytosanitaryView.as_view()),
         name='phytosanitary_view'),
    path('<int:garden_id>/create_phytosanitaire', access_private_garden(CreatePhytosanitaryView.as_view()),
         name='create_phytosanitary_entry'),
    path('<int:garden_id>/delete_phytosanitaire/<int:pk>', access_private_garden(DeletePhytosanitaryView.as_view()),
         name='delete_phytosanitary_entry'),
    path('<int:garden_id>/edit_phytosanitaire/<int:pk>', access_private_garden(UpdatePhytosanitaryView.as_view()),
         name='update_phytosanitary_entry'),
    path('<int:garden_id>/create_phytosanitaire_usage', access_private_garden(CreatePhytosanitaryUsage.as_view()),
         name='create_phytosanitary_usage'),
    path('<int:garden_id>/delete_phytosanitaire_usage/<int:pk>',
         access_private_garden(DeletePhytosanitaryUsage.as_view()),
         name='delete_phytosanitary_usage'),
    path('<int:garden_id>/edit_phytosanitaire_usage/<int:pk>',
         access_private_garden(UpdatePhytosanitaryUsage.as_view()),
         name='update_phytosanitary_usage'),

    # Contact modal
    path('contact', ContactView.as_view(), name='contact_info'),

]

research/urls.py
from django.urls import path

from research import views
from research.custom_decorators import researcher_permission_required
from research.views import GardensView, VegetablesView, ExportGardens, LibraryView, ExportLibraryOperations, \
    ExportLibraryVarieties, ExportLibrarySpecies, ExportVegetablesData

app_name = 'research'

urlpatterns = [
    path('', researcher_permission_required()(GardensView.as_view()), name='all_gardens_view'),
    path('export_gardens', researcher_permission_required()(ExportGardens.as_view()), name='export_gardens_data'),
    path('export_vegetables_data', researcher_permission_required()(ExportVegetablesData.as_view()), name='export_vegetables_data'),
    path('vegetables', researcher_permission_required()(VegetablesView.as_view()), name='all_vegetables_view'),

    path('library', researcher_permission_required()(LibraryView.as_view()), name='vegetables_library_view'),
    path('export_library', researcher_permission_required()(ExportLibraryOperations.as_view()), name='export_library'),
    path('export_library_species', researcher_permission_required()(ExportLibrarySpecies.as_view()),
         name='export_library_species'),
    path('export_library_varieties', researcher_permission_required()(ExportLibraryVarieties.as_view()),
         name='export_library_varieties'),
    path('logout', views.log_out, name="log_out"),
]

research/views/gardens_data_views.py
import codecs
import csv
from datetime import date

from django.contrib.auth.models import User
from django.http import HttpResponse
from django.views import View
from django.views.generic import TemplateView

from planner.models import Garden


class GardensView(TemplateView):
    template_name = 'research/gardens.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the gardens
        gardens = Garden.objects.filter(details_available_for_research=True)
        context['gardens'] = gardens
        return context


# def garden_as_pdf(request):
#     # https://rumpelsepp.github.io/2014/09/23/generating-pdfs-with-django-and-latex.html
#     gardens = Garden.objects.filter(details_available_for_research=True)
#     context = {
#         'gardens': gardens,
#     }
#     template = get_template('research/latex_template.tex')
#     rendered_tpl = template.render(context).encode('utf-8')
#     # Python3 only. For python2 check out the docs!
#     with tempfile.TemporaryDirectory() as tempdir:
#         # Create subprocess, supress output with PIPE and
#         # run latex twice to generate the TOC properly.
#         # Finally read the generated pdf.
#         for i in range(2):
#             process = Popen(
#                 ['pdflatex', '-output-directory', tempdir],
#                 stdin=PIPE,
#                 stdout=PIPE,
#             )
#             process.communicate(rendered_tpl)
#         with open(os.path.join(tempdir, 'texput.pdf'), 'rb') as f:
#             pdf = f.read()
#     r = HttpResponse(content_type='application/pdf')
#     # r['Content-Disposition'] = 'attachment; filename=texput.pdf'
#     r.write(pdf)
#     return r


class ExportGardens(View):

    def get(self, request, **kwargs):
        return export_gardens_data()


def export_gardens_data():
    gardens = Garden.objects.filter(details_available_for_research=True)
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    filename = "gardens_data_{}.csv".format(str(date.today()))
    response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
    response.write(codecs.BOM_UTF8)
    writer = csv.writer(response, delimiter=';', dialect='excel', quoting=csv.QUOTE_ALL)
    writer.writerow(
        ['Nom du jardin', 'Code Postal', 'Adresse email', 'Description', 'Type de sol', 'Agriculture', 'Utilisateurs'])
    for h in gardens:
        n = len(User.objects.filter(garden=h))
        writer.writerow(
            [h.name, h.postal_code, h.reference_email, h.comment, h.soil_type, h.culture_type, n])
    return response

research/views/library_views.py
from datetime import date

from django.views import View
from django.views.generic import TemplateView

from planner.import_vegetables_helpers import get_csv_writer
from vegetables_library.models import Variety, CulturalOperation, COWithDate, Species


class LibraryView(TemplateView):
    template_name = 'research/library_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['library_varieties'] = Variety.objects.all().order_by('species__french_name')
        return context


class ExportLibraryOperations(View):
    def get(self, request, **kwargs):
        return export_library_data()


class ExportLibraryVarieties(View):
    def get(self, request, **kwargs):
        return export_library_varieties()


class ExportLibrarySpecies(View):
    def get(self, request, **kwargs):
        return export_library_species()


def export_library_varieties():
    library_vegetables = Variety.objects.all()
    filename = "vegetable_library_varieties_{}.csv".format(str(date.today()))
    (writer, response) = get_csv_writer(filename)
    writer.writerow(
        ['Espèce', 'Variété FR', 'Variété LATIN', 'Début semis', 'Fin semis', 'Début récolte', 'Fin récolte',
         'Durée du cycle', 'Note'])
    for h in library_vegetables:
        writer.writerow([h.species.french_name, h.french_name, h.latin_name, h.open_ground_seeding.seeding_start,
                         h.open_ground_seeding.seeding_end, h.open_ground_seeding.harvest_start,
                         h.open_ground_seeding.harvest_end, h.open_ground_seeding.cycle_duration, h.comment])
    return response


def export_library_species():
    library_vegetables = Species.objects.all()
    filename = "vegetable_library_species_{}.csv".format(str(date.today()))
    (writer, response) = get_csv_writer(filename)
    writer.writerow(
        ['Espèce FR', 'Espèce LATIN', 'Famille', 'Type'])
    for h in library_vegetables:
        writer.writerow([h.french_name, h.latin_name, h.family, h.vegetable_type])
    return response


def export_library_data():
    library_vegetables = Variety.objects.all()
    filename = "vegetable_library_data_{}.csv".format(str(date.today()))
    (writer, response) = get_csv_writer(filename)
    writer.writerow(
        ['Légume', 'Variété', 'Operation', 'Date', 'Delai', 'Operation précédente'])
    for h in library_vegetables:
        for co in CulturalOperation.objects.select_subclasses().filter(vegetable=h):
            if isinstance(co, COWithDate):
                writer.writerow([h.name, h.variety, co.name, co.get_date(), "", ""])
            else:
                writer.writerow([h.name, h.variety, co.name, "", co.offset_in_days, co.previous_operation.name])
    return response

research/views/logout.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect


def log_out(request):
    logout(request)
    return HttpResponseRedirect("/login")

research/views/vegetables_data_views.py
from datetime import date

from django.views import View
from django.views.generic import TemplateView

from planner.import_vegetables_helpers import get_csv_writer


class VegetablesView(TemplateView):
    template_name = 'research/vegetables.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        from planner.models import Vegetable as gardens_vegetables
        vegetables = gardens_vegetables.objects.filter(garden__activity_data_available_for_research=True)
        context['vegetables'] = vegetables
        from vegetables_library.models import Variety as library_vegetables
        library_vegetables = library_vegetables.objects.all()
        context['library_vegetables'] = library_vegetables
        return context


class ExportVegetablesData(View):
    def get(self, request, **kwargs):
        return export_vegetables_data()


def export_vegetables_data():
    filename = "donnees_legumes_jardins_{}.csv".format(str(date.today()))
    writer, response = get_csv_writer(filename)
    from planner.models import Vegetable as gardens_vegetables
    from planner.models import CulturalOperation as gardens_operations
    vegetables = gardens_vegetables.objects.filter(garden__activity_data_available_for_research=True)
    operations = gardens_operations.objects.select_subclasses().filter(vegetable__in=vegetables)
    writer.writerow(
        ['Jardin', 'Jardin id', 'Espèce', 'Variété', 'Opération à faire', 'Id de opération', 'Date de réalisation',
         'Offset (jours)',
         'Opération précédente', 'Id opération précédente'])

    from planner.models import COWithDate as gardens_cowithdate
    for h in operations:
        if isinstance(h, gardens_cowithdate):
            writer.writerow(
                [h.vegetable.garden.name, h.vegetable.garden_id, h.vegetable.name, h.vegetable.variety, h.name, h.id,
                 h.get_date().strftime('%d-%m'), '', '', ''])
        else:
            writer.writerow(
                [h.vegetable.garden.name, h.vegetable.garden_id, h.vegetable.name, h.vegetable.variety, h.name,
                 h.id, h.get_date().strftime('%d-%m'), h.offset_in_days, h.previous_operation.name, h.previous_operation.id])
    return response

research/templates/research/gardens.html
{% extends 'research/base.html' %}

{% block content %}
    {% load research_extras %}

    <div class="modal fade" id="modal-export_history" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-export_harvests" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-export_phytosanitary_usage" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>
    <div class="modal fade" id="modal-export_phytosanitary_entries" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>

    <div id="action-buttons">
        <div class="fab-btn btn-group show-on-hover dropup">
            <div data-toggle="tooltip" data-placement="right" title="Exporter" style="margin-left: 42px;">
                <a href="{% url 'research:export_gardens_data' %}">
                    <button class="btn btn-primary btn-io">
                    <span class="">
                      <i class="fas fa-w fa-download"></i>
                    </span>
                    </button>
                </a>
            </div>
        </div>
    </div>

    <table class="table table-hover table-bordered table-responsive ">
        <tr>
            <th> Jardins</th>
            <th>Adresse de contact</th>
            <th> Détails</th>
            <th> Données téléchargeables</th>
        </tr>
        {% for g in gardens %}
            <tr>
                <td class="col-md-3">
                    {{ g.name }}
                </td>
                <td class="col-md-3">
                    {% if g.reference_email %}
                        {{ g.reference_email }}
                    {% else %}
                        Pas d'adresse email communiquée
                    {% endif %}
                </td>
                <td>
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action">
                            <b>Code postal : </b>
                            {{ g.postal_code }}
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <b>Description : </b>
                            {{ g.comment }}
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <b>Type de sol : </b>
                            {{ g.soil_type }}
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <b> Type d'agriculture pratiquée : </b>
                            {{ g.culture_type }}
                        </li>
                        <li class="list-group-item list-group-item-action">
                            <b> Nombre d'utilisateurs : </b>
                            {% get_garden_number_users g %}
                        </li>
                    </ul>
                </td>
                <td>

                    {% if g.activity_data_available_for_research %}
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-action">
                            L'historique des actions de ce jardin
                            <a href="{% url 'planner:garden_history_export_view' g.id %}" class="pull-right"
                               data-toggle="modal"
                               data-target="#modal-export_history"
                               title="Exporter l'historique des actions de ce jardin" data-tooltip>
                                <i class="fas fa-fw fa-upload"></i>
                            </a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            Les données de récoltes de ce jardin
                            <a href="{% url 'planner:garden_harvest_export_view' g.id %}" class="pull-right"
                               data-toggle="modal"
                               data-target="#modal-export_harvests"
                               title="Exporter les données de récoltes de ce jardin" data-tooltip>
                                <i class="fas fa-fw fa-upload"></i>
                            </a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            Le registre d'entrée de produits phytopharmaceutiques
                            <a href="{% url 'planner:garden_entry_register_export' g.id %}" class="pull-right"
                               data-toggle="modal"
                               data-target="#modal-export_phytosanitary_entries"
                               title="Exporter le registre d'entrée de produits phytopharmaceutiques" data-tooltip>
                                <i class="fas fa-fw fa-upload"></i>
                            </a>
                        </li>
                        <li class="list-group-item list-group-item-action">
                            Le registre d'utilisation de produits phytopharmaceutiques
                            <a href="{% url 'planner:garden_usage_register_export' g.id %}" class="pull-right"
                               data-toggle="modal"
                               data-target="#modal-export_phytosanitary_usage"
                               title="Exporter le registre d'utilisation de produits phytopharmaceutiques" data-tooltip>
                                <i class="fas fa-fw fa-upload"></i>
                            </a>
                        </li>

                    </ul>
                    {% else %}
                        <p> Cette exploitation n'accepte pas de partager ses données de travail</p>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    {% load static %}
    <script src="{% static 'planner/js/activate_modal.js' %}"></script>
    <script src="{% static 'planner/js/activate_tooltips.js' %}"></script>
{% endblock content %}

research/templates/research/library_view.html
{% extends 'research/base.html' %}

{% block content %}
    {% load research_extras %}
    <h2> Légumes dans la bibliothèque </h2>


    <div id="action-buttons">
        <div class="fab-btn btn-group show-on-hover dropup">
            <div data-toggle="tooltip" data-placement="right" title="Import-Export" style="margin-left: 42px;">
                <button type="button" class="btn btn-danger btn-io dropdown-toggle" data-toggle="dropdown">
                    <span class="">
                      <i class="fas fa-fw fa-ellipsis-h"></i>
                    </span>
                </button>
            </div>
            <ul class="dropdown-menu dropdown-menu-right" role="menu">
                <li data-toggle="tooltip" data-original-title="Télécharger les espèces" data-placement="right">
                    <a class="btn btn-success"
                       href="{% url "research:export_library_species" %}">
                        <i class="fas fa-fw fa-book"></i>
                    </a>
                </li>
                <li data-toggle="tooltip" data-original-title="Télécharger les variétés" data-placement="right">
                    <a class="btn btn-success"
                       href="{% url "research:export_library_varieties" %}">
                        <i class="fas fa-fw fa-seedling"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>


    {% load humanize %}
    <div class="container">
        <div class="form-group">
            <input class="form-control" id="search_input" type="text" placeholder="Rechercher..">
        </div>
        <div class="row card-deck" id="searchable_element">
            {% for v in library_varieties %}
                <div class="card-container searchable-container col-sm-12 col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title searchable">{{ v.species }} - {{ v.french_name }} </h4>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Action</th>
                                        <th>Début</th>
                                        <th> Fin</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td> Semis</td>
                                        <td>{{ v.open_ground_seeding.seeding_start|date:"j F" }}</td>
                                        <td>{{ v.open_ground_seeding.seeding_end|date:"j F" }}</td>
                                    </tr>
                                    <tr>
                                        <td> Récolte</td>
                                        <td>{{ v.open_ground_seeding.harvest_start|date:"j F" }}</td>
                                        <td>{{ v.open_ground_seeding.harvest_end|date:"j F" }}</td>
                                    </tr>

                                    {% for co in v.id|vegetable_operations %}
                                        <tr>
                                            <td> {{ co.name }}</td>
                                            <td></td>
                                            <td>{{ co.get_date|date:"j F" }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>

                                </table>
                            </div>
                        </div>
                        <div class="card-footer">
                            <p> Durée du cycle : {{ v.open_ground_seeding.cycle_duration }} jours </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>



    {% load static %}
    <script src="{% static 'planner/js/activate_tooltips.js' %}"></script>
    <script src="{% static 'planner/js/search_elements.js' %}"></script>

{% endblock content %}

research/templates/research/vegetables.html
{% extends 'research/base.html' %}

{% block content %}
    {% load research_extras %}
    {% load humanize %}


    <div id="action-buttons">
        <div class="fab-btn btn-group show-on-hover dropup">
            <div data-toggle="tooltip" data-placement="right" title="Exporter" style="margin-left: 42px;">
                <a href="{% url 'research:export_vegetables_data' %}">
                    <button class="btn btn-primary btn-io">
                    <span class="">
                      <i class="fas fa-w fa-download"></i>
                    </span>
                    </button>
                </a>
            </div>
        </div>
    </div>


    <h2> Légumes utilisés dans les jardins </h2>
    <table class="table table-hover table-bordered table-responsive ">
        <tr>
            <th> Jardin</th>
            <th>Légume - Variété</th>
            <th> Itinéraire technique</th>
        </tr>
        {% for v in vegetables %}
            <tr>
                <td class="col-md-3">
                    {{ v.garden.name }}
                </td>
                <td class="col-md-3">
                    {{ v.name }} - {{ v.variety }}
                </td>
                <td>
                    <ul>
                        {% for o in v.id|garden_vegetable_operations %}
                            <li>
                                {{ o.name }} - {{ o.get_date|date:"j F" }}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
    </table>


    {% load static %}
    <script src="{% static 'planner/js/activate_tooltips.js' %}"></script>

{% endblock content %}